version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
  promethius:
    image: "prom/prometheus"
    ports:
      - '9090:9090'
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  cassandra:
    image: "cassandra"
    ports:
      - "7000:7000"
  zipkin-storage:
    image: openzipkin/zipkin-mysql
    container_name: mysql
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/tree/1.19.0/zipkin-server#environment-variables
    environment:
      - STORAGE_TYPE=mysql
      # Point the zipkin at the storage backend
      - MYSQL_HOST=mysql
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
      # Uncomment if you set SCRIBE_ENABLED=true
    depends_on:
      - zipkin-storage
  app:
    image: matomo:fpm
    links:
      - db
    volumes:
      - ./config:/var/www/html/config:rw
      - /home/your-logs-folder:/var/www/html/logs
    env_file:
      - ./matomo.env
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST
